
server:
  port: 8002


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/iorderdb
    username: root
    password: Since2019#
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: order_service
  config:
    import: configserver:http://localhost:8051




